avstplg: Fix incorrect usage of nullable type
Address the following exception:

  InvalidOperationException: "Nullable object must have a value."

by operating on the array directly. Value of 'Kcontrols?'
may be null and accessing Length property in such case is invalid.

Fixes: 259d2ddbe150 ("avstplg: Add kcontrol support")
Signed-off-by: Cezary Rojewski <cezary.rojewski@intel.com>